package reconcile

import (
	"testing"
	"time"

	"github.com/pocketbase/pocketbase/core"

	"context"

	"github.com/north-shore-software/kalaido/kalaidoscope/internal/api"
	"github.com/north-shore-software/kalaido/kalaidoscope/internal/engine"
	"github.com/north-shore-software/kalaido/kalaidoscope/internal/llmcontext"
	"github.com/north-shore-software/kalaido/kalaidoscope/internal/pbutil"
	"github.com/north-shore-software/kalaido/kalaidoscope/internal/status"
	"github.com/north-shore-software/kalaido/kalaidoscope/internal/testutil"
)

// A scheduled reflection's elapsed windows are generated by the wave and must
// then settle: the evaluator resumes from the max approved window end, not
// from an arbitrary "latest" snapshot (whose approval sequence counts per
// window and whose window_spec holds the schedule, not the bounds).
func TestWaveSettlesScheduledReflectionWindows(t *testing.T) {
	app := testutil.NewApp(t)
	ctx := context.Background()

	testutil.NewRecord(t, app, "fragment", map[string]any{"type": "note", "content": "x"})

	spec := api.ContextSpec{WholeScope: true}
	lens := newLens(t, app, spec)
	// Weekly window, created ~3 weeks ago -> 3 pending windows.
	created := time.Now().Add(-21 * 24 * time.Hour)
	versions := engine.AppendWindowSpecVersion(nil, api.WindowSpec{Period: "168h"}, created)
	refl := testutil.NewRecord(t, app, "reflection", map[string]any{
		"name":                 "R",
		"current_context_spec": pbutil.JSONObject(spec),
		"current_lens_id":      lens.Id,
		"window_spec_versions": pbutil.JSONObject(versions),
	})
	// Backdate created so window anchoring starts 3 weeks ago.
	if _, err := app.DB().NewQuery("UPDATE reflection SET created = {:c} WHERE id = {:id}").
		Bind(map[string]any{"c": created.UTC().Format("2006-01-02 15:04:05.000Z"), "id": refl.Id}).Execute(); err != nil {
		t.Fatalf("backdate: %v", err)
	}

	report := func(label string) []api.Window {
		statuses, err := status.NewEvaluator(app, time.Now()).EvaluateAll(ctx)
		if err != nil {
			t.Fatalf("evaluate: %v", err)
		}
		for _, s := range statuses {
			if s.ID == refl.Id {
				t.Logf("%s: pendingWindows=%d newFrags=%d upToDate=%q", label, len(s.PendingWindows), len(s.NewFragmentIDs), s.UpToDateSnapshotID)
				return s.PendingWindows
			}
		}
		t.Fatalf("%s: reflection not in statuses", label)
		return nil
	}

	// An initial approved snapshot so the evaluator engages (drafts are
	// ignored). Windowless, like a first manual generation.
	newApprovedSnapshot(t, app, "reflection_snapshot", "reflection_id", refl.Id, lens.Id,
		pinnedAllFragments(t, app))
	time.Sleep(2 * time.Millisecond)

	report("before wave")
	runWave(app)
	snaps := snapshotsFor(t, app, "reflection_snapshot", "reflection_id", refl.Id)
	t.Logf("after wave: %d snapshots", len(snaps))
	for _, s := range snaps {
		t.Logf("  snap wk=%q seq=%d status=%s", s.GetString("window_key"), s.GetInt("approval_sequence_number"), s.GetString("status"))
	}
	after := report("after wave")
	if len(after) != 0 {
		t.Errorf("pending windows did not settle: %d remain", len(after))
	}

	// A second wave must not regenerate anything.
	before := countAllSnapshots(t, app)
	time.Sleep(2 * time.Millisecond)
	runWave(app)
	if got := countAllSnapshots(t, app); got != before {
		t.Errorf("second wave grew snapshots %d -> %d", before, got)
	}
}

func pinnedAllFragments(t *testing.T, app core.App) llmcontext.PinnedIDs {
	t.Helper()
	recs, err := app.FindRecordsByFilter("fragment", "1=1", "", 0, 0)
	if err != nil {
		t.Fatalf("fragments: %v", err)
	}
	var ids []string
	for _, r := range recs {
		ids = append(ids, r.Id)
	}
	return llmcontext.PinnedIDs{FragmentIDs: ids}
}
